# Generated by Django 6.1 on 2026-08-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('website', models.CharField(blank=True, default='', max_length=2048)),
                ('http_status', models.PositiveIntegerField(blank=True, null=True)),
                ('page_title', models.TextField(blank=True, default='')),
                ('meta_description', models.TextField(blank=True, default='')),
                ('heading_count', models.PositiveIntegerField(default=0)),
                ('h1_count', models.PositiveIntegerField(default=0)),
                ('image_count', models.PositiveIntegerField(default=0)),
                ('images_without_alt', models.PositiveIntegerField(default=0)),
                ('link_count', models.PositiveIntegerField(default=0)),
                ('seo_score', models.FloatField(default=0)),
                ('technical_seo_score', models.FloatField(default=0)),
                ('accessibility_score', models.FloatField(default=0)),
                ('security_score', models.FloatField(default=0)),
                ('performance_score', models.FloatField(default=0)),
                ('overall_score', models.FloatField(default=0)),
                ('advanced_seo_score', models.FloatField(default=0)),
                ('title_length', models.PositiveIntegerField(default=0)),
                ('description_length', models.PositiveIntegerField(default=0)),
                ('canonical_url', models.TextField(blank=True, null=True)),
                ('viewport', models.TextField(blank=True, default='')),
                ('og_title', models.BooleanField(default=False)),
                ('og_description', models.BooleanField(default=False)),
                ('og_image', models.BooleanField(default=False)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('ai_insights', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
